name: deploy website
on:
  push:
    branches: 
      - master
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Output event data
        run: echo "Hi Test"
  build:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Output event data
        run: echo "Hi Build"
      - name: print pwd
        run: echo $pwd
      - name: copy file
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: "ss-xml/*" # Include all files inside the ss-xml folder
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Output event data
        run: echo "Hi Deploy"
